version: '3'

services:
  # mongodb:
  #   container_name: mongodb
  #   image: mongo:latest
  #   environment:
  #     - MONGODB_DATABASE="test"
  #   ports:
  #     - 27017:27017
  #   networks:
  #     - default
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default

networks:
  default:
    driver: bridge
